# Generated by Django 3.0.7 on 2020-07-21 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conta', models.IntegerField()),
                ('numero_agencia', models.IntegerField()),
                ('titular', models.CharField(max_length=100)),
                ('saldo', models.FloatField()),
                ('data_criacao_conta', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'conta_cliente',
            },
        ),
    ]
