# Generated by Django 3.0.7 on 2020-07-22 00:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operador_contas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='titular',
            new_name='nome_titular',
        ),
        migrations.AlterModelTable(
            name='conta',
            table=None,
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimentacao', models.CharField(choices=[('D', 'DEBITO'), ('C', 'CREDITO')], max_length=1)),
                ('valor', models.FloatField()),
                ('descricao', models.CharField(max_length=144)),
                ('data_ocorrencia', models.DateTimeField(default=datetime.datetime.now)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao', to='operador_contas.Conta')),
            ],
        ),
    ]
